### PR TITLE
Develop with mmdet2.1.0

### PR DESCRIPTION
**Pull request by Ilya-Krylov**

### CODE REVIEW

**Comment by Ilya-Krylov** [comment]
run tests

**Comment by Ilya-Krylov** [comment]
run tests

**Comment by Ilya-Krylov** [comment]
run tests

**Comment by Ilya-Krylov** [comment]
run tests

**Comment by Ilya-Krylov** [comment]
@AlexanderDokuchaev could you please remove following line wherever it comes from 
pip install git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI

it is from http://134.191.240.124/job/ote/job/precommit/job/mmdetection/110/console

Authors of mmdetection changed 'official' pycocotools on their pycocotools fork.
@druzhkov-paul FYI

**Comment by AlexanderDokuchaev** [comment]
>@AlexanderDokuchaev could you please remove following line wherever it comes from
pip install git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI

@Ilya-Krylov done

**Comment by Ilya-Krylov** [comment]
run tests

**Comment by Ilya-Krylov** [comment]
@AlexanderDokuchaev thanks

**Comment by Ilya-Krylov** [comment]
@druzhkov-paul

**Review by druzhkov-paul — APPROVED** [review]

**Pull request merged**
