### PR TITLE
ONNX export fixes

### PR DESCRIPTION
**Pull request by druzhkov-paul**

### CODE REVIEW

**Comment by druzhkov-paul** [comment]
run tests

**Comment by druzhkov-paul** [comment]
run tests

**Comment by druzhkov-paul** [comment]
run tests

**Comment by druzhkov-paul** [comment]
run tests

**Comment by druzhkov-paul** [comment]
run tests

**Comment by druzhkov-paul** [comment]
run tests

**Comment by druzhkov-paul** [comment]
@Ilya-Krylov please review

**Review by Ilya-Krylov — APPROVED** [review]

**Pull request merged**
