### PR TITLE
Remove requirement on eval and fixed evaluation in case of IR

### PR DESCRIPTION
**Pull request by Ilya-Krylov**

### CODE REVIEW

**Comment by Ilya-Krylov** [comment]
run tests

**Comment by Ilya-Krylov** [comment]
run tests

**Comment by Ilya-Krylov** [comment]
run tests

**Comment by Ilya-Krylov** [comment]
run tests

**Comment by Ilya-Krylov** [comment]
@druzhkov-paul please have a look

**Review by druzhkov-paul — APPROVED** [review]

**Pull request merged**
