### PR TITLE
Update nncf prerelease 2.0.3

### PR DESCRIPTION
**Pull request by AlexanderDokuchaev**

### CODE REVIEW

**Comment by AlexanderDokuchaev** [comment]
ci - 364 🟢

**Review by alexsu52 — CHANGES_REQUESTED** [review]
Please wait for the final validation

**Comment by druzhkov-paul** [comment]
@AlexanderDokuchaev @alexsu52 What's the status of this?

**Comment by alexsu52** [comment]
it's not relevant.

**Pull request closed without merging**
