### PR TITLE
Update readmes

### PR DESCRIPTION
**Pull request by druzhkov-paul**

### CODE REVIEW

**Review by Ilya-Krylov — APPROVED** [review]

**Review by AlexanderDokuchaev — APPROVED** [review]

**Comment by AlexanderDokuchaev** [comment]
One question, did you think about OVDetection (openvino) or OCVDetection (opencv)?

**Comment by Ilya-Krylov** [comment]
@AlexanderDokuchaev hren redki ne slashe. @druzhkov-paul Merge?

**Comment by Ilya-Krylov** [comment]
run tests

**Comment by Ilya-Krylov** [comment]
run tests

**Pull request merged**
