### PR TITLE
enable HPO for OTE_cli (brave_new_world)

### PR DESCRIPTION
**Pull request by e-ddykim**
This PR is for enabling HPO for OTE_cli (brave_new_world).
The list of changes are as follows:

* 'hpo_config.yaml' file are added for each model.
* Some codes are changed to pass the validation score every epoch via OTE_SDK's standard API.

### CODE REVIEW

**Comment by druzhkov-paul** [comment]
@e-ddykim Thanks for your contribution. Please set source and target branches properly before we go on with a review.

**Comment by e-ddykim** [comment]
> @e-ddykim Thanks for your contribution. Please set source and target branches properly before we go on with a review.

@druzhkov-paul Currently, the source branch is based on the commit that is linked to the latest brave_new_world. Could you tell me which branch to pick as target?

**Comment by druzhkov-paul** [comment]
Please use `dp/nous_sdk_api` as the target. And also push your source branch to this repo (this is a limitation of the current CI pipeline).

**Comment by e-ddykim** [comment]
> Please use `dp/nous_sdk_api` as the target. And also push your source branch to this repo (this is a limitation of the current CI pipeline).

@druzhkov-paul I can't change the source branch to this repo. So I created a new PR in https://github.com/openvinotoolkit/mmdetection/pull/223 .

**Pull request closed without merging**
