### PR TITLE
Revert #136

### PR DESCRIPTION
**Pull request by AlexanderDokuchaev**
Revert "Fix wrapping outputs. Replacement original forward for forward export. #136"

#136 Fixed wrapping output issue but broke accuracy after initialization of quantization because batch for init_dataloader set 1.

### CODE REVIEW

**Comment by AlexanderDokuchaev** [comment]
run tests

**Review by kshpv — APPROVED** [review]

**Review by asenina — APPROVED** [review]

**Comment by druzhkov-paul** [comment]
run tests

**Comment by druzhkov-paul** [comment]
So, is my understanding correct, that outputs' quantization will not work after merging the PR? Is it used for any OTE model? Are you going to propose another fix for that?

**Comment by asenina** [comment]
> So, is my understanding correct, that outputs' quantization will not work after merging the PR? Is it used for any OTE model? Are you going to propose another fix for that?

Yes, it is. This option `quantize_output` will not work after merging this PR. As far as i know we don't use it to quantize OTE model (but there is a request from external users). I will continue to fix this problem. Now it look like the only possible solution is to extend the `simple_test` in such a way that this function can works with a batch >=1 (In this case the changes that are reverted in this PR will return again).

**Review by druzhkov-paul — APPROVED** [review]

**Comment by druzhkov-paul** [comment]
@asenina @AlexanderDokuchaev @kshpv Moving forward, as you are improving NNCF integration and fixing bugs, could you please consider the possibility to enable NNCF w/o any changes to the core mmdet part and prefer that kind of design choices in the first place. Thanks.

**Pull request merged**
