### PR TITLE
Add no_nncf_trace() for postprocessing in single stage detector

### PR DESCRIPTION
**Pull request by kshpv**
Face-detector-205 should work with this PR

### CODE REVIEW

**Review by LeonidBeynenson — APPROVED** [review]

**Comment by LeonidBeynenson** [comment]
2 @druzhkov-paul : just FYI

**Comment by Ilya-Krylov** [comment]
This branch is out-of-date with the base branch

**Comment by kshpv** [comment]
> This branch is out-of-date with the base branch

Rebased

**Comment by Ilya-Krylov** [comment]
run tests

**Comment by Ilya-Krylov** [comment]
run tests

**Review by druzhkov-paul — APPROVED** [review]

**Pull request merged**
