### PR TITLE
Add license file to deployed archive

### PR DESCRIPTION
**Pull request by LeonidBeynenson**

### CODE REVIEW

**Comment by LeonidBeynenson** [comment]
Note that this PR is draft until PR https://github.com/openvinotoolkit/training_extensions/pull/859 is merged
(That PR contains the required LICENSE file)

**Review by Ilya-Krylov — APPROVED** [review]

**Comment by LeonidBeynenson** [comment]
Hi all

@Ilya-Krylov , @druzhkov-paul , please, merge this PR, since 
* the only function that is changed is the function `deploy`, 
* the function `deploy` is checked by the test `test_ote_deploy_openvino`
* the test is run in OTE
* I made PR https://github.com/openvinotoolkit/training_extensions/pull/860 and run checks for it
  -- and all checks are passed, including all `test_ote_deploy_openvino` tests!

So, I'm sure that it is safe to merge this PR.

**Comment by LeonidBeynenson** [comment]
See all the checks here
http://213.221.44.203/job/ote/job/precommit/job/ote_sdk_tests_runner/384/console

**Comment by druzhkov-paul** [comment]
@akorobeinikov FYI

**Review by druzhkov-paul — APPROVED** [review]

**Pull request merged**
