### PR TITLE
Remove sklearn install

### PR DESCRIPTION
**Pull request by sungmanc**

### CODE REVIEW

**Comment by sungmanc** [comment]
@harimkang @goodsong81 , Could you check this?

**Comment by harimkang** [comment]
Any problem with this?
image

**Comment by sungmanc** [comment]
> Any problem with this? image

Yes, scikit-learn also can be imported by `import sklearn`

This PR includes the validation report: https://github.com/openvinotoolkit/training_extensions/pull/1512

**Comment by harimkang** [comment]
> Yes, scikit-learn also can be imported by `import sklearn`
> 
> This PR includes the validation report: [openvinotoolkit/training_extensions#1512](https://github.com/openvinotoolkit/training_extensions/pull/1512)

Shouldn't these imports also be removed for remove `sklearn`?

**Comment by sungmanc** [comment]
> > Yes, scikit-learn also can be imported by `import sklearn`
> > This PR includes the validation report: [openvinotoolkit/training_extensions#1512](https://github.com/openvinotoolkit/training_extensions/pull/1512)
> 
> Shouldn't these imports also be removed for remove `sklearn`?

What we want to delete is `sklearn`, but we also still want to use `scikit-learn`. 
With the `scikit-learn`, we can use `import sklearn.***`

**Review by harimkang — APPROVED** [review]
Ah yes I understand.

**Pull request merged**
