### PR TITLE
Update NNCF version to 1.7.0

### PR DESCRIPTION
**Pull request by LeonidBeynenson**

### CODE REVIEW

**Comment by LeonidBeynenson** [comment]
run tests

**Comment by LeonidBeynenson** [comment]
2 @druzhkov-paul : Pavel, could you merge this PR? Aleksei Kashapov and me worked on the latest NNCF during last weeks and everything was OK.

**Comment by LeonidBeynenson** [comment]
Please, note that this change could _significantly_ improve speed of tests, since the latest NNCF contains the fix of the bug "rebuild NNCF extensions every time"

**Review by Ilya-Krylov — APPROVED** [review]

**Comment by druzhkov-paul** [comment]
@LeonidBeynenson 

> Pavel, could you merge this PR?

It's better to request a review, rather that asking for merge. The hope for fast merge is always there, but why is it? :smile:

> note that this change could significantly improve speed of tests

Like a word of a marketing god. It could or it does? And you mean like bring it back to the normal level, or really make it faster? :smile:

**Review by druzhkov-paul — APPROVED** [review]

**Comment by Ilya-Krylov** [comment]
2 @LeonidBeynenson everything has been broken in OTE.

**Comment by druzhkov-paul** [comment]
@LeonidBeynenson please combine your fixes with #121 to merge them together.

**Pull request merged**
