### PR TITLE
add tiling module

### PR DESCRIPTION
**Pull request by eugene123tw**
## Tile Dataset
* Add `ImageTilingDataset` dataset wrapper
* Add `class Tile` for cropping a full-res image to small tiles and aggregating tile prediction before evaluation. 

## Config Example
```
tile_cfg = dict(tile_size=320, min_area_ratio=0.9, overlap_ratio=0.25, iou_threshold=0.45, max_per_img=200)

train_pipeline = [
    dict(type='Resize', img_scale=(416, 416), keep_ratio=False),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Pad', size_divisor=416),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]

test_pipeline = [
    dict(type='MultiScaleFlipAug',
         img_scale=(416, 416),
         flip=False,
         transforms=[
             dict(type='Resize', keep_ratio=False),
             dict(type='RandomFlip'),
             dict(type='Normalize', **img_norm_cfg),
             dict(type='Pad', size_divisor=416),
             dict(type='ImageToTensor', keys=['img']),
             dict(type='Collect', keys=['img'])
         ])
]

val_dataset = dict(type='ImageTilingDataset',
                   dataset=dict(
                       type='CocoDataset',
                       test_mode=True,
                       pipeline=[dict(type='LoadImageFromFile')]),
                   pipeline=test_pipeline,
                   **tile_cfg)

train_dataset = dict(
    type='ImageTilingDataset',
    dataset=dict(
        type='CocoDataset',
        pipeline=[
            dict(type='LoadImageFromFile', to_float32=True),
            dict(type='LoadAnnotations', with_bbox=True)]),
    pipeline=train_pipeline,
    **tile_cfg)


data = dict(samples_per_gpu=36,
            workers_per_gpu=4,
            train=train_dataset,
            val=val_dataset)
```

### CODE REVIEW

**Comment by druzhkov-paul** [comment]
run tests

**Comment by druzhkov-paul** [comment]
I've changed the target branch. Please submit PRs to it until it's merged. Please rebase now. Sorry for any inconvenience.

**Review by eugene123tw — COMMENTED** [review]
@druzhkov-paul no worries, I've rebased the branch to the new base branch.

**Comment by eugene123tw** [comment]
run tests

**Comment by nervana-ff** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
