### PR TITLE
Hide NNCF imports

### PR DESCRIPTION
**Pull request by druzhkov-paul**
For some reason import of NNCF takes a lot of time (~1 minute). And that holds true for *every* script run that uses mmdet, but not only the first one in a clean environment. This PR proposes a workaround to import NNCF iff it is really required, hence minimizing the impact of this on non-NNCF-powered tasks.

### CODE REVIEW

**Comment by druzhkov-paul** [comment]
run tests

**Comment by LeonidBeynenson** [comment]
From my point of view, it looks very-very good.
I want to re-review it one more time, and then I will accept it.

**Comment by kshpv** [comment]
@druzhkov-paul nice changes! 
At the same time new release version of NNCF will no longer have the problem with rebuilding extensions. The root cause of this issue is a bug in PyTorch. But our team could make a workaround to resolve it.

**Review by kshpv — APPROVED** [review]

**Comment by druzhkov-paul** [comment]
> new release version of NNCF will no longer have the problem with rebuilding extensions.

Cool. It'd be beneficial to use it as it comes out and prove to work smoothly. Thanks for the fast response on this.

**Comment by druzhkov-paul** [comment]
run tests

**Review by LeonidBeynenson — APPROVED** [review]

**Comment by LeonidBeynenson** [comment]
@druzhkov-paul : Pavel, I approved this PR.
Should we wait until the CI finishes its work?
The changes were checked earlier, and the changes are in those part of code that is not covered by mmdetection CI

**Comment by druzhkov-paul** [comment]
run tests

**Comment by LeonidBeynenson** [comment]
2 @druzhkov-paul : Pavel, I updated this PR (added one commit) to fix the issue with wrong NNCF import.
(Sorry that updated your PR without preliminary notification)

I use this branch in OTE PR https://github.com/openvinotoolkit/training_extensions/pull/530 "Use pytest as a unittest runner" -- I updated external/mmdetection submodule in OTE to the current head of this branch.
This will allow to check if my fix works -- if the CI for that OTE PR is green tomorrow, then everything is OK.

**Pull request merged**
