### PR TITLE
Upstream master branch merge

### PR DESCRIPTION
**Pull request by DmitriySidnev**
This is the upstream master branch merge.
- [x] Run tests
- [x] Test inference and quality of all available models
- [x] Check training

* All tests passed successfully excluding the one with deformable convolutions
* All models inference successfully
* Found that `SABL` and `YoloV3` have significant metrics drop (supposedly because of `nms`) while others have the same metrics as reference ones in upstream
* Some models have incorrect metrics in readme files or incorrect checkpoints
* Export to ONNX of new models: not tested
* `NNCF`: not tested

### CODE REVIEW

**Comment by druzhkov-paul** [comment]
I found it more convenient to compare the branch to the upstream master (at a respective commit). So I've left comments if a dummy PR here: https://github.com/druzhkov-paul/mmdetection/pull/3. I've started the review there just to keep my own notes, but it turned out that most of them are more of discussion topics. Please take a look there and sorry for any inconvenience.

**Comment by DmitriySidnev** [comment]
run tests

**Comment by DmitriySidnev** [comment]
run tests

**Comment by DmitriySidnev** [comment]
run tests

**Comment by DmitriySidnev** [comment]
run tests

**Comment by DmitriySidnev** [comment]
run tests

**Comment by DmitriySidnev** [comment]
run tests

**Comment by DmitriySidnev** [comment]
run tests

**Comment by DmitriySidnev** [comment]
run tests

**Comment by DmitriySidnev** [comment]
run tests

**Comment by DmitriySidnev** [comment]
run tests

**Comment by DmitriySidnev** [comment]
run tests

**Comment by DmitriySidnev** [comment]
run tests

**Comment by DmitriySidnev** [comment]
run tests

**Comment by DmitriySidnev** [comment]
run tests

**Review by druzhkov-paul — APPROVED** [review]

**Comment by DmitriySidnev** [comment]
run tests

**Pull request merged**
