### PR TITLE
Urgent fix: packages conflict with ote_cli

### PR DESCRIPTION
**Pull request by LeonidBeynenson**

### CODE REVIEW

**Comment by druzhkov-paul** [comment]
@LeonidBeynenson please elaborate. Does mmdetection have ipython in dependencies at all?

**Comment by LeonidBeynenson** [comment]
Additional Info: 
* due to update of ipython and other packages, now the latest ipython uses `typing-extensions >=3.10.0.0`
* when `ote-cli` package is installed, it uses `nbmake` that uses `ipykernel` that uses `ipython >= 7.23.1` -- it installs the latest ipython by default
* in ~our~ mmdetection constraints.txt we have `typing-extensions==3.7.4.3`
* moreover, e2e test system requires the same `typing-extensions==3.7.4.3`
* as the result when ote-cli is installed with constraints of mmdetection, it goes to almost-infinite loop of searching proper package combination
* so, the simplest decision is to point the precise version of `ipython`
* it is the only change in this PR

**Comment by LeonidBeynenson** [comment]
Also see the PR https://github.com/openvinotoolkit/training_extensions/pull/894

**Comment by druzhkov-paul** [comment]
Is it possible to specify this constraint for OTE CLI, not OTEDetection? OTE CLI is even not installed in init_venv.sh.

**Comment by LeonidBeynenson** [comment]
It is possible, but, please, note that constraints file is the tool to point compatible combination of requirements that may be installed may be not
See in [the documentation](https://pip.pypa.io/en/stable/user_guide/#constraints-files):
>  there is one key difference: Including a package in a constraints file does not trigger installation of the package.

Since mmdetection's constraint file points `typing-extensions==3.7.4.3`, then the same constraint file should point compatible version of other packages (e.g. ipython)

**Review by druzhkov-paul — APPROVED** [review]

**Pull request merged**
