### PR TITLE
Moving reallive training tests to OTE SDK test helpers

### PR DESCRIPTION
**Pull request by LeonidBeynenson**

### CODE REVIEW

**Comment by LeonidBeynenson** [comment]
Note that this PR should be considered together with this OTE PR
https://github.com/openvinotoolkit/training_extensions/pull/754
since now test helpers are moved to OTE SDK

**Comment by druzhkov-paul** [comment]
@LeonidBeynenson please trigger CI build.

**Comment by LeonidBeynenson** [comment]
> @LeonidBeynenson please trigger CI build.

Build 161 succeeded. ✔️

**Comment by LeonidBeynenson** [comment]
Resolved conflicts, merged dp/nous_sdk_api to this branch.
Build 171 is run. :runner:

**Comment by LeonidBeynenson** [comment]
Build 171 is succeeded ✔️

**Comment by LeonidBeynenson** [comment]
2 @Ilya-Krylov , @druzhkov-paul  -- could you merge this PR?

**Comment by druzhkov-paul** [comment]
`2 @Ilya-Krylov , @druzhkov-paul -- could you merge this PR?`

Not now. Does this PR address changes made in #261?

**Comment by LeonidBeynenson** [comment]
Build 190 is run 🏃

**Comment by LeonidBeynenson** [comment]
> Not now. Does this PR address changes made in #261?
@druzhkov-paul I moved this change to OTE SDK.  
Yes, now `template*.yaml` is used in globbing.
See it here: https://github.com/openvinotoolkit/training_extensions/blob/9df76377a64c4bc2afdd7a227dc617ba7f1c917b/ote_sdk/ote_sdk/test_suite/fixtures.py#L138

**Comment by LeonidBeynenson** [comment]
Build 190 succeeded. ✔️

**Comment by LeonidBeynenson** [comment]
~~2 @druzhkov-paul , Pavel, since all the changes for this PR and PR https://github.com/openvinotoolkit/training_extensions/pull/754 are done, and build succeeded, please, merge this PR!~~

~~(But please, note that PR https://github.com/openvinotoolkit/training_extensions/pull/754 should be merged after that ASAP, otherwise CI will not work.)~~

Ooops, I found out that another PR has been merged, so I should resolve merge conflicts right now

**Comment by LeonidBeynenson** [comment]
Resolved merge conflicts, merged HEAD of the branch dp/nous_sdk_api to this branch.
The build 193 is run. 🏃

**Comment by LeonidBeynenson** [comment]
2 @druzhkov-paul , @Ilya-Krylov , please let's merge this PR if the build 193 succeeds.

(And note that when this PR is merged, the PR openvinotoolkit/training_extensions#754 should be updated after the merge and then it should be merged ASAP, otherwise CI will not work.)

Tomorrow I'll be ready for the merges and I really ask you not to merge other PR-s before, since otherwise the next round of the "Achilles and the Tortoise" game will be started.

**Comment by LeonidBeynenson** [comment]
Build 193 passed ✔️ 
Merged the dp/nous_sdk_api to this branch
Build 195 is run 🏃

**Comment by LeonidBeynenson** [comment]
Build 195 is failed in `end_to_end` test due to random nature of the test.
Build 196 is run. 🏃

**Comment by Ilya-Krylov** [comment]
@druzhkov-paul  consider merging this PR, OTE SDK part has been merged

**Comment by LeonidBeynenson** [comment]
@druzhkov-paul , please 🙏 , merge this PR
Build 196 is passed. ✔️

**Review by druzhkov-paul — APPROVED** [review]

**Pull request merged**
