### PR TITLE
Export stubs cleaning

### PR DESCRIPTION
**Pull request by druzhkov-paul**
Removed anchor generator stubs. Work with OpenVINO 2020.4.

### CODE REVIEW

**Comment by druzhkov-paul** [comment]
run tests

**Comment by druzhkov-paul** [comment]
run tests

**Comment by druzhkov-paul** [comment]
@Ilya-Krylov please review. Please note, that this has been tested with PyTorch 1.5.1 only.

**Comment by druzhkov-paul** [comment]
run tests

**Review by Ilya-Krylov — APPROVED** [review]

**Comment by druzhkov-paul** [comment]
run tests

**Pull request merged**
