### PR TITLE
Update visualization for OV inferencer

### PR DESCRIPTION
**Pull request by akorobeinikov**

### CODE REVIEW

**Comment by druzhkov-paul** [comment]
Build 250 🔴

**Comment by druzhkov-paul** [comment]
@akorobeinikov tests failed.

**Comment by akorobeinikov** [comment]
> @akorobeinikov tests failed.

Because I changed converters in [PR](https://github.com/openvinotoolkit/training_extensions/pull/775)

**Comment by druzhkov-paul** [comment]
Build 264 ✔️

**Comment by druzhkov-paul** [comment]
This should be merged together with https://github.com/openvinotoolkit/training_extensions/pull/775

**Review by Ilya-Krylov — APPROVED** [review]

**Pull request merged**
